### ISSUE TITLE
[FEATURE] Can't save mail server information

### ISSUE THREAD

**Issue by notfixingit3** [utmstack/UTMStack#111]
**Describe the bug**
Can't save mail server settings without providing a username and password. Internal forwarding mail server is restricted by IP and does not use username/password authentication.

**Expected behavior**
Save mail server settings without requiring user and password

**Environment**
Ubuntu 22.04
Chrome, Safari
v10.0.0

**Comment by leonardomoralopez89** [comment]
I confirm that all configuration parameters associated with the email are mandatory.
