### ISSUE TITLE
[BUG] Source/Destination details not correct

### ISSUE THREAD

**Issue by amanzella** [utmstack/UTMStack#122]
I have installed the windows agent on a few servers and when the alerts come through, for example Windows: Probable Password guessing, the Source Details in the GUI shows my server's hostname and IP and the destination shows the username that was attempted. However, shouldn't the source show the info for the person that was trying to guess the password and the destination show my server info? In the log, under event_data, it has the IpAddress of the person attempting to login. I don't see in the log where it shows the port though, although we know it was RDP since we opened RDP for testing.

**Comment by Kbayero** [comment]
@amanzella Send us an example of the alerts where this problem occurs, and in turn logs related to this alert. Make sure not to pass on sensitive information

**Comment by amanzella** [comment]
@Kbayero @osmontero This is still happening. Here is one example.

<img width="839" alt="Screenshot 2024-02-16 at 7 38 45 PM" src="https://github.com/utmstack/UTMStack/assets/14251074/8473127b-5243-4a4b-8746-be39405edd04">
<img width="839" alt="Screenshot 2024-02-16 at 7 38 37 PM" src="https://github.com/utmstack/UTMStack/assets/14251074/979bd9bd-db8c-465b-8c0c-7f5e4cfdb671">
<img width="839" alt="Screenshot 2024-02-16 at 7 38 25 PM" src="https://github.com/utmstack/UTMStack/assets/14251074/c97cf7ab-acae-4f66-8548-918dc3cf2b36">
<img width="839" alt="Screenshot 2024-02-16 at 7 38 10 PM" src="https://github.com/utmstack/UTMStack/assets/14251074/22ce10cb-ee0d-411c-a6a8-d2dc2cb0c7a0">
