### ISSUE TITLE
[BUG] Filebrowser stay as if it will be doing something, but it has already done the job

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#171]
**Describe the bug**
When you go to the correlation rules manager view and upload a file/folder the screen stays gray even if the upload was terminated

**To Reproduce**
1. Go to 'Manage correlation rules' from the lateral right menu
2. Try to upload or download a file/folder
4. See the gray screen

**Expected behavior**
After the upload or download the screen must be white as the begins

**Screenshots**
![image](https://github.com/utmstack/UTMStack/assets/17603499/fa974313-6a70-47dc-85c4-09411618487e)
![image](https://github.com/utmstack/UTMStack/assets/17603499/33938fab-0f6d-45d1-802d-bc16a7683bc3)

**Environment**
 - UTMStack v10 dev

**Comment by mjabascal10** [comment]
Fixed issue in https://github.com/utmstack/filebrowser
