### ISSUE TITLE
[BUG] Visualizations failing

### ISSUE THREAD

**Issue by Kbayero** [utmstack/UTMStack#185]
GCP User Activity has only one Visualization and the counter cannot be at 0 because there are logs
![image](https://github.com/utmstack/UTMStack/assets/99102374/39ac2370-4c55-4ecd-a858-e1e294a560e9)

![image](https://github.com/utmstack/UTMStack/assets/99102374/58cc9ba4-01f9-4efc-bb46-9f33b7c721f3)

**Comment by jdieguez89** [comment]
@Kbayero did you check the visualization filters??, probably the visualization is filtered by a specific event, and the log explorer is listing all logs from the last 24 hours

**Comment by Kbayero** [comment]
The visualization is filtered by an event that has not occurred for days, that explains the counter at 0.
