### ISSUE TITLE
[BUG] Agents are not showing CONSOLE label

### ISSUE THREAD

**Issue by Kbayero** [utmstack/UTMStack#189]
**Describe the bug**
Agents should display the console label indicating that datasource is an agent. However, when clicking on the datasource it does show the agent data and allows commands to be executed.

**To Reproduce**
1. Go to Data Sources
2. Click on an Agent Details

**Screenshots**
![image](https://github.com/utmstack/UTMStack/assets/99102374/007d485d-9f0b-4b72-b30a-359e077ce632)
![image](https://github.com/utmstack/UTMStack/assets/99102374/bef63a7d-f2d9-464a-99eb-42c4c5f99b88)

**Environment**
 - Version v10.2.0

**Comment by Kbayero** [comment]
For some reason, when making the request to the backend to obtain the data sources, we get agent: false. However, this is an agent and the Agent Manager does have it as a registered agent
![image](https://github.com/utmstack/UTMStack/assets/99102374/ed830fce-53b0-485a-8d52-fa613df7b618)
![image](https://github.com/utmstack/UTMStack/assets/99102374/71552ac7-b750-47ff-b947-f35b642ff5ea)

**Comment by leonardomoralopez89** [comment]
The problem here is that the data sources have not been marked as agents for those assets that are agents due to a sync problem for duplicate asset names in agents.
