### ISSUE TITLE
[BUG] Frontend is making continuous requests when logout 

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#260]
**Describe the bug**
After you logout from the application, the frontend is still making continuous nonsense requests to the account endpoint

**To Reproduce**
1. Login into the application
2. Press F12 and go to console
3. Logout from the application

**Expected behavior**
Stop sending this endpoint calls

**Screenshots**
![image](https://github.com/utmstack/UTMStack/assets/17603499/d1d0ccfc-e713-4364-9a55-5154686c9106)

**Environment**
 - UTMStack QA

**Comment by jdieguez89** [comment]
@mjabascal10 This issue is because some Subscriptions to the account observer have not been closed, please take a look
