### ISSUE TITLE
[BUG] Configuring an SSL/TLS certificate section in documentation goes to wrong URL

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#287]
**Describe the bug**
In the documentation, Configuring an SSL/TLS certificate links to the wrong place -> https://docs.utmstack.com/Installation/FirewallRules

**To Reproduce**
1. Go to 'https://docs.utmstack.com/Installation/MasterServerInstallation.html'
2. Click on 'Configuring an SSL/TLS certificate'
3. See that goes to https://docs.utmstack.com/Installation/FirewallRules

**Expected behavior**
Points to the Configuring an SSL/TLS certificate section -> https://docs.utmstack.com/Installation/SSLConfiguration.html

**Comment by alaynsn89** [comment]
Solved
