### ISSUE TITLE
[BUG] Integration disconnected alert coming too often

### ISSUE THREAD

**Issue by rvald26** [utmstack/UTMStack#313]
**Describe the bug**
The alert of disconnected integration is too repetitive.
<img width="1084" alt="image" src="https://github.com/utmstack/UTMStack/assets/37116247/1b82c1b3-d6a7-4b3c-a35b-210aef2fc236">

**To Reproduce**
Setup Bitdefender antivirus integration.
Block the connection somehow
Wait for the panel to start detecting the connection down.

**Expected behavior**
After the first alert, it should only alert again once every 24 hours.

**Screenshots**

**Environment**
UTMSTack 10.1

**Comment by leonardomoralopez89** [comment]
On it
