### ISSUE TITLE
[BUG] string field contains invalid UTF-8 sophos

### ISSUE THREAD

**Issue by balajiuma2736** [utmstack/UTMStack#329]
2024/01/19 10:02:24 UTMStackAgent ERROR: Error sending logs to Log Auth Proxy: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

**Comment by osmontero** [comment]
Hey, thanks for your report. Could you make it in the format of the bug report template and provide the contextual information?

**Comment by jdieguez89** [comment]
Hi @balajiuma2736, Can you please provide more context about this issue? We were not able to duplicate the issue in our environments

**Comment by balajiuma2736** [comment]
sophos logs are pushing to utmstack but it giving errors on utf8 invaild.

Balaji
________________________________

**Comment by c3s4rfred** [comment]
Poor information about the issue
