### ISSUE TITLE
[BUG] Incorrect Linux Agent install command

### ISSUE THREAD

**Issue by rvald26** [utmstack/UTMStack#333]
**Describe the bug**
Linux command requires "sudo su" before executing.

**To Reproduce**
Executing the command as it is provided in the Linux integration guide will fail. 

sudo apt update -y && sudo apt install wget -y && mkdir -p /opt/utmstack-linux-agent && wget -P /opt/utmstack-linux-agent https://cdn.utmstack.com/agent_updates/release/installer/v10.2.0/utmstack_agent_installer && chmod -R 777 /opt/utmstack-linux-agent/utmstack_agent_installer && sudo /opt/utmstack-linux-agent/utmstack_agent_installer install v10-dev.utmstack.com ************************************************************************ yes

**Possible solution**
Change the guide and include a "sudo su" command before executing the agent install. Remove "sudo" from the installation command.

**Environment**
 All versions

**Comment by Kbayero** [comment]
This bug has been solved and tested correctly
