### ISSUE TITLE
[BUG] Command copy is confusing

### ISSUE THREAD

**Issue by rvald26** [utmstack/UTMStack#334]
**Describe the bug**
Some times users will not use the copy functionality available besides the command in the windows or linux integration box. Instead, sometimes users just highlight the text and Ctrl+C it leading to incorrect command with market key **********

**Expected behavior**
Selecting text inside the command box should not be possible. Only option to copy the text should be copying it using the copy button.

**Screenshots**
Incorrect usage we should prevent:
<img width="937" alt="image" src="https://github.com/utmstack/UTMStack/assets/37116247/7d367909-0398-438c-a764-c4a46199407c">

Correct use we should encourage:
<img width="921" alt="image" src="https://github.com/utmstack/UTMStack/assets/37116247/4becf27c-a1e0-4852-b3d3-5d3b267b44b0">

**Environment**
All

**Comment by jdieguez89** [comment]
@rvald26 changing to enhancement, the copy button is clearly visible

**Comment by jdieguez89** [comment]
@rvald26 this enhancement will be released in version 10.3.0; it has already been implemented and tested.
Closing this issue
