### ISSUE TITLE
[BUG] UTMStack installer should check for Docker IP range conflict

### ISSUE THREAD

**Issue by rvald26** [utmstack/UTMStack#341]
**Describe the bug**
UTMStack install fails because of a conflict with the IP range of the customer network.

**To Reproduce**
Install UTMStack in a network with 172.16.0.1/16 and 172.17.0.1/16 IP ranges

**Expected behavior**
The installer should automatically detect possible conflict and use a different network range for docker CT.

**Environment**
UTMStack 10.2

**Comment by osmontero** [comment]
Docker automatically detects when the default CIDR is in use during installation and uses a different CIDR for the bridge interface.
