### ISSUE TITLE
[BUG] Sophos XG integration doesn't work

### ISSUE THREAD

**Issue by secureme71** [utmstack/UTMStack#37]
**Describe the bug**
I have enabled "Sophos XG" integration like UTMStack v9 and it doesn't work because I don't see any firewall source.

**To Reproduce**
I have simply enabled the "Sophos XG" integration and firewall sends udp packet on port 514 to UTMStack.
The setting of Sophos firewall is:
UDP port 514
Daemon
Debug
Legacy mode (because native mode doesn't work on UTMStack)

**Environment**
 - UTMStack 10 is on Ubuntu 22.04
 - Sophos Firewall 19.5.3 MR3

**Comment by secureme71** [comment]
I don't know if the issue is related to integration because I have tried to reinstall the UTMStack and I have following issue:

Installing Stack [OK]
Waiting for Backend to be ready. This may take a while.
Waiting for Backend to be ready [OK]
Sending sample logs
Post "http://127.0.0.1:10000/v1/newlog": dial tcp 127.0.0.1:10000: connect: connection refused

**Comment by osmontero** [comment]
Our team is resolving this issue and a fix will be released in version 10.1.

**Comment by osmontero** [comment]
About this error: 'Post "http://127.0.0.1:10000/v1/newlog": dial tcp 127.0.0.1:10000: connect: connection refused', can you please send us the result of executing the following command?

`docker service logs utmstack_correlation`

**Comment by secureme71** [comment]
The output of command "docker service logs utmstack_correlation" is empty.

**Comment by osmontero** [comment]
That means that the correlation engine is not working, common causes are insufficient resources (CPU and memory) and also a network problem, where the port used by the correlation engine is already in use by another service, or that Docker could not lock it for use.

**Comment by osmontero** [comment]
In version 10.1 we have made multiple changes to the pipeline, and we tested this integration and everything is working correctly. Please reconfigure the integration following the steps in the guide, make sure to look at the guide because there have been changes.

**Comment by secureme71** [comment]
I have opened another issue after upgrade or fresh installation of UTMStack v.10.1 so I cannot verify your resolution.

However my VM has 16vCPU and 64Gb ram. I have no issue with version 9.x
