### ISSUE TITLE
[BUG] Documentation of correlation rules is outdated for v10.2

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#399]
**Describe the bug**
The correlation rule's documentation is outdated in https://docs.utmstack.com/Correlation%20Rules/README.html, at the current version 10.2 we have a rule field called "dataTypes" that isn't present in the documentation

**Possible solution**
Add dataTypes field in fields reference -> https://docs.utmstack.com/Correlation%20Rules/README.html#fields-reference after "tactic" field definition, with this description - > Group of datatypes applied to a rule, means that only the logs with dataType field matching with at least one of these values will be processed by this rule. This field is an array of string values, so, you can place more than one value separated by comma.

In the example section -> https://docs.utmstack.com/Correlation%20Rules/README.html#examples put -> dataTypes: ["wineventlog"] below "tactic" field

**Comment by alaynsn89** [comment]
Solved
