### ISSUE TITLE
[BUG] Federation Service Installation guide is wrong

### ISSUE THREAD

**Issue by jdieguez89** [utmstack/UTMStack#400]
![image](https://github.com/utmstack/UTMStack/assets/26327410/43ba1952-ede2-454e-84a6-939a14502dbf)

Change 

wget https://github.com/AtlasInsideCorp/UTMStackFSInstaller/releases/latest/download/UTMStackFSInstaller.zip

to 

wget https://github.com/utmstack/UTMStackFSInstaller/releases/download/v10.0.0/UTMStackFSInstaller.zip

**Comment by alaynsn89** [comment]
Solved
