### ISSUE TITLE
[FEATURE] Implementation of Secret Management for Incident Response Commands

### ISSUE THREAD

**Issue by jdieguez89** [utmstack/UTMStack#403]
**Is your feature request related to a problem? Please describe.**
Currently, when executing incident response commands that require secure information (like API keys or tokens), we don't have a standardized and safe way to include these sensitive elements. This leads to potential security risks as sensitive data might be exposed or mishandled.

**Describe the solution you'd like**
I propose the implementation of a feature that allows the creation of 'secrets' - similar to environment variables - that can be securely stored and accessed within our system. These secrets should be easily configurable and usable as placeholders in incident response commands. For example, if a command requires an API key in the header, it should be able to reference a secret containing this key rather than the key being explicitly written in the command.

**Additional context**
Implementing this feature would significantly enhance the security and efficiency of our incident response processes. It aligns with best practices for handling sensitive data and would make our system more robust against potential security breaches. This feature would also align our system with common industry standards for secure data handling in automated processes.

**Comment by jdieguez89** [comment]
![image](https://github.com/utmstack/UTMStack/assets/26327410/b4a0e855-9aed-480e-a8b4-e0ace832f6f2)


![image](https://github.com/utmstack/UTMStack/assets/26327410/62a1fb01-2f69-42f0-870e-0fa16271558d)

![image](https://github.com/utmstack/UTMStack/assets/26327410/8d9677d2-4ac7-4bba-a99e-d1574f4101a9)

![image](https://github.com/utmstack/UTMStack/assets/26327410/9c42a72d-d53e-4e48-94df-b08ba2db1cf5)

**Comment by alaynsn89** [comment]
solved
