### ISSUE TITLE
[BUG] o365 integration return a 500 internal error in some prod environments

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#406]
**Describe the bug**
o365 integration returns a 500 internal error from backend in some prod environments when trying to connect from the container 

**To Reproduce**
The issue was in production, we were unable to reproduce it in our dev environments so far.

**Screenshots**
![image](https://github.com/utmstack/UTMStack/assets/17603499/fcb30faf-dc74-4474-b4b4-7ed2346f436a)

**Environment**
 - UTMStack 10.2

**Possible solution**
Seems to be a problem with the user's configuration in the instance, upgrade to latest version

**Comment by c3s4rfred** [comment]
We have already tested several times in our environments, there is nothing as far that can be causing that behavior, it's only happening in that client's environment so, we will schedule a meeting to check the logs to clarify the situation

**Comment by osmontero** [comment]
Could not be reproduced. Performed multiple restart tests, reconfiguration, clean installation, etc.
