### ISSUE TITLE
[BUG] Validate minimum time of one day in cron expressions for scheduled reports

### ISSUE THREAD

**Issue by mjabascal10** [utmstack/UTMStack#435]
Currently, the system allows the creation of scheduled reports with time configurations less than a day. This undesired functionality impacts the application's performance, generating an excess of reports and resulting in an overflow of email notifications

**To Reproduce**
1. Go to 'Compliance'
2. Click on 'Schedule Report'
3. Click on 'New Schedule'
4. Select Compliance report and go next step
5. Click on Create Compliance

**Screenshots**
![2024-02-08_171518](https://github.com/utmstack/UTMStack/assets/20338555/99aae800-4dbb-4d01-af94-b30f204bed8f)

**Possible solution**
The solution involves implementing a validation to prevent the addition of time configurations less than one day for scheduled reports.

**Comment by alaynsn89** [comment]
in process
