### ISSUE TITLE
[BUG] Using UTMStack alert tagging and grouping for multiple customers

### ISSUE THREAD

**Issue by rvald26** [utmstack/UTMStack#528]
**Describe the bug**
It is always recommended to use one UTMStack VM per customer, however, sometimes specific scenarios allow for multiple customers to be monitored with a single instance. When this happens, customers use tags to differentiate one alert customer from another. For example, 1.x.x.x network range belongs to customer A and 2.x.x.x belongs to customer B. Using this logic it is possible to differentiate alerts from multiple customers.

This "bug" exists when customer A has an alert show up in the list of alerts, then customer B has an alert with the same name. Even though both customer A and B got their respective tags, their alerts were grouped together as related logs.

**Expected behavior**
Alerts that receive different tags should not be grouped.

**Environment**
10.x

**Comment by osmontero** [comment]
Hello,

Thank you for reaching out to us.

Unfortunately, UTMStack was not designed as a multi-tenant server. If you require this feature, you will need to launch a separate UTMStack instance for each tenant and then use the federation server to manage multiple instances from one central location.

Please note that this is not a highly requested feature, but if enough users request it, we may add it to our roadmap.

Thank you for your understanding.
