### ISSUE TITLE
[BUG] Quick start documentation to open ports is outdated

### ISSUE THREAD

**Issue by c3s4rfred** [utmstack/UTMStack#598]
**Describe the bug**
 The ports in Quick Start documentation is wrong.  

**To Reproduce**
1. Go to 'https://docs.utmstack.com/QuickStart.html' -> Configure a Windows Agent DataSource -> Pre-installation Requirements
2. See the ports to open, are wrong.

**Expected behavior**
It must be 9000 and 50051 for agents.

**Screenshots**
![image](https://github.com/utmstack/UTMStack/assets/17603499/cfbd07e3-6761-4d3b-8f6c-a0a8477ab349)

**Environment**
 - Documentation

**Comment by Lacak-SK** [comment]
Can you then please also explain what type of communication takes place through these ports ...
