### ISSUE TITLE
[BUG] Meraki logs not being filtered

### ISSUE THREAD

**Issue by RathHunt** [utmstack/UTMStack#686]
Describe the bug

Cisco Meraki logs are not being caught by the Logstash filter. The logs remain in the generic category despite attempts to filter them.

To Reproduce

Send Meraki logs to the utmstack agent
See that the logs are not being filtered and remain in the generic category

Expected behavior

The expected behavior is that the Cisco Meraki logs would be filtered out from the generic category and categorized appropriately.

Screenshots

![image](https://github.com/utmstack/UTMStack/assets/71412426/71381cfd-1ee4-48e0-a47a-6ba488cfa593)

Environment

OS: [Please specify]
Browser: [Please specify]
Version: [Please specify]
Additional context

The specific log entry that was tested is: 1377449842.514782056 MX84 ids-alerts signature=129:4:1 priority=1 timestamp=1377449842.512569 direction=ingress protocol=tcp/ip src=74.125.140.132:80

**Comment by c3s4rfred** [comment]
The log wasn't sent with the correct format, also the integration wasn't active.
