### ISSUE TITLE
Installing Windows Agent Returns an Error

### ISSUE THREAD

**Issue by apixler77** [utmstack/UTMStack#731]
**Describe the bug**

When trying to install a Windows agent on version 10.5.2 returns the error "one or more of the required ports are closed. Please open ports 9000 and 50051.

**To Reproduce**

1. Run Power Shell Command as administrator
2. Error is produced.

**Expected behavior**

The agent should install all dependencies and report to the server.

![UTMStack Agent Istall Error](https://github.com/utmstack/UTMStack/assets/166551483/e62ce8b3-5806-4a79-bebe-953a65833b5e)

 - OS: Windows 11, Ubuntu 22.04, VMWare Workstation

 - Version 10.5.2

**Comment by osmontero** [comment]
This is not a bug, the error makes it clear what the problem is. You must make sure that the server or workstation where you are installing the agent can see both ports of the UTMStack server.
