### ISSUE TITLE
Possible incorrect link in README

### ISSUE THREAD

**Issue by goetzk** [utmstack/UTMStack#790]
**Describe the bug**

The readme says
```
We have a [dedicated repository]([https://github.com/AtlasInsideCorp/UTMStackCorrelationRules](https://github.com/utmstack/rules))  for correlation rules, contributors are welcome to submit a pull request. 
```
That repository is a 404.

**To Reproduce**

1. Go to https://github.com/utmstack/UTMStack
2. Click on 'dedicated repository'
3. See error

**Expected behavior**

A repository with rules is displayed

**Possible solution**

I suspect the new location is https://github.com/utmstack/rules but because that repository doesn't describe what it is in the description or readme I can't be 100% certain.

**Comment by c3s4rfred** [comment]
Hi, @goetzk you're right that URL is from old repository, the new one is https://github.com/utmstack/rules, but will be deprecated from version 11.0.0.

Best regards

**Comment by goetzk** [comment]
> Hi, @goetzk you're right that URL is from old repository, the new one is https://github.com/utmstack/rules, but will be deprecated from version 11.0.0.
> 
> Best regards

Thanks for the response! Will rules all be brought in to the main repository going forward?

**Comment by osmontero** [comment]
Yes, starting with v11, base rules, log transformation scripts, and plugins will be hosted in the main repository.

**Comment by osmontero** [comment]
Fixed in https://github.com/utmstack/UTMStack/commit/32994c8a7af175a62336604eb990dc45de0177a9
