### ISSUE TITLE
utmstack-v10-1-0-autoinstall.iso error checksum

### ISSUE THREAD

**Issue by Celestine-delalt** [utmstack/UTMStack#810]
When launching the installer from the utmstack-v10-1-0-autoinstall.iso on a Proxmox VM, the installation fails. It reports "The install media checksum verification failed. It's possible that this crash is related to that checksum failure. Consider verifying the install media and retrying the install."

Confirmed that the md5sum for the ISO matches what's provided in iso/utmstack-v10-1-0-autoinstall.md5 on https://cdn.utmstack.com/:
634e4c320b932a603ac6f6472e524e58  utmstack-v10-1-0-autoinstall.iso

I found this in the installation logs:
ubuntu-server casper-md5check: Checking ./boot/grub/grub.cfg ..... /boot/grub/grub.cfg: mismatch.

In the md5sum.txt on the root directory of the ISO, it has the following entry:
	f617054321761f742970fdd0165e1034  ./boot/grub/grub.cfg

Checking the MD5 sum of the /boot/grub/grub.cfg on the ISO shows it does not match the entry:
    md5sum ./boot/grub/grub.cfg
    fb84b39613316f393030dfda8aa4c329  ./boot/grub/grub.cfg

Is there a problem with the current ISO installer that is available on the website?

_Originally posted by @sysmedent in https://github.com/utmstack/UTMStack/discussions/807_

**Comment by c3s4rfred** [comment]
This is fixed and was answered to the client by a ticket.
