### ISSUE TITLE
[BUG] OpenSearch "Connection Refused" on new Installs

### ISSUE THREAD

**Issue by brandonmedihost** [utmstack/UTMStack#828]
**Edit: Looks like its magically working again. Suspect it had something to do with a recent 2.16.0 OpenSearch ontainer. 

When performing a new install on Ubuntu using the installer, it will fail on 'Initializing OpenSearch'

**To Reproduce**

1. Brand new Ubuntu VM
2. Runinstaller from [Quick Start Page](https://docs.utmstack.com/QuickStart.html)
3. Wait for installer to start OpenSearch

**Expected behavior**
Installer would proceed without error. OpenSearch would start. UTMStack Admin Page would become available.

**Screenshots**
![image](https://github.com/user-attachments/assets/bd225143-d56e-4478-a646-733236caad60)

**Environment**

 - OS: Ubuntu 22.04.5 LTS and Ubuntu 24.04 Server
 - Browser: Chrome
 - Version: Latest

**Additional context**
Have tried with different VM resourcing sizes (CPU/RAM/Disk)
Have tried on different VM Host with different CPU Type

**Possible solution**
Possibly an update to the OpenSearch container which is pulled by the installer? 
(Can run the installer on an already deployed system which has pulled the containers already)

**Comment by demirozmustafa** [comment]
How to solutions?

**Comment by demirozmustafa** [comment]
What is solutions?
