### ISSUE TITLE
[FEATURE]  offer pure bash installer and linux agnostic agent config

### ISSUE THREAD

**Issue by commandline-be** [utmstack/UTMStack#860]
**Is your feature request related to a problem? Please describe.**

the options offered to install an agent are specific to an OS 
the agent does not start because the Linux OS is not recognised
Linux agents should be considered distro agnostic since LSB is available

preferably UTMstack should be distro agnostic and LSB compliant instead of distro centric

**Describe the solution you'd like**

because the agent install script require to install wget this fails on so called non-supported OS
recommendation is to have the install script check for wget and on 'not found' opt to use a package manager
this way the agent can install without failing on the package manager

the agent does not start if the OS/distro is considered not supported while this is actually Elastic beats agent known to run

**Describe alternatives you've considered**

since giving UTMstack a go such lack of flexibility is a show stopper for adoption

**Additional context**

**Comment by c3s4rfred** [comment]
Closed because the UTMStack's linux agents can't be linux agnostic. LSB is deprecated, see -> https://lists.linuxfoundation.org/pipermail/lsb-discuss/2023-February/008278.html

Best regards
