### ISSUE TITLE
Portal Username and Password Error

### ISSUE THREAD

**Issue by erkanbuyukbayraktaroglu** [utmstack/UTMStack#899]
I have installed the UTMStack ISO. I can manage the server via the web interface at https://serveripaddress:9090 using the username and password utmstack/utmstack. However, when I access it through https://serveripaddress, the UTMStack Login screen does not accept any credentials. I tried logging in with admin/admin or utmstack/utmstack, but unfortunately, I was not successful. Could you please help me?

**Comment by osmontero** [comment]
Please, follow the steps in the installation guide, the last step is to get the installation details including the initial administrator password.

[Step 6](https://docs.utmstack.com/Installation/InstallfromIso.html#step-6-finalize-installation-and-access-the-web-interface)

**Comment by erkanbuyukbayraktaroglu** [comment]
In Step 5, I found the admin username and password in the file located at the path: /home/utmstack/installer.log using the command
Thank you for your support.
