### ISSUE TITLE
[BUG] Unable to change status to complete if observations contain french characters

### ISSUE THREAD

**Issue by ubidev** [utmstack/UTMStack#902]
**Describe the bug**

Unable to change status to complete if description contains french characters

**To Reproduce**

- Click alert status
- Choose "Complete"
- Type a french character in observations. ex: "é"
- Apply Status
- Status remains unchanged

**Expected behavior**

I should be able to type my observations in another language than English

**Environment**

 - OS: Ubuntu 24.04.1 LTS
 - Browser: Latest MS Edge
 - Version: 10.5.16

Thanks in advance and have a great whatever you're doing right now :)

**Comment by osmontero** [comment]
@mjabascal10 please try to replicate this issue.

**Comment by ubidev** [comment]
Hi there :) ,

What do you mean?

Every time I change de status of an alert to Complete, inserting a  french non ascii character like "é" reports success (green toast) but the status remains unchange, every attemp. Removing the offending character yields success, every time.

**Comment by ubidev** [comment]
I can confirm that it is fixed :)
